spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/user
    password: admin123
  jpa:
    show-sql: 'true'
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update
