spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/user
    password: admin123
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: 'true'
    hibernate:
      ddl-auto: none
server:
  port: 8082

aw:
  auth:
    provider-uri: "http://localhost:8082"
    jks:
      keypass: 123456
      storepass: 123456
      alias: awblog
      path: keystore/awblog.jks